#### general settings
name: panx2_3
use_tb_logger: True
model: sr
distortion: sr
scale: 2
save_img: False
gpu_ids: [3]

#### datasets
datasets:
  train:
    name: DF2K
    mode: LQGT
    dataroot_GT: '/home/mldai/workspace/IKS/PAN/datasets/DIV2K/DIV2K_train_HR_X2'
    dataroot_LQ: '/home/mldai/workspace/IKS/PAN/datasets/DIV2K/DIV2K_train_LR_bicubic/X2'

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 32
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Set5
    mode: LQGT
    dataroot_GT: ../datasets/Set5/HR
    dataroot_LQ: ../datasets/Set5/LR_bicubic/X2

#### network structures
network_G:
  which_model_G: PAN
  in_nc: 3
  out_nc: 3
  nf: 40
  unf: 24
  nb: 16
  scale: 2

#### path
path:
  pretrain_model_G: /home/mldai/workspace/IKS/PAN/experiments/pretrained_models/PANx2_DF2K.pth
  strict_load: False
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
#  CCAR
#  lr_G: !!float 7e-4
#  lr_scheme: CosineAnnealingLR_Restart
#  beta1: 0.9
#  beta2: 0.99
#  niter: 100000
#  warmup_iter: -1  # no warm up
#  T_period: [25000, 25000, 25000, 25000]
#  restarts: [25000, 50000, 75000]
#  restart_weights: [1, 1, 1]
#  eta_min: !!float 1e-7

# MSLR
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 200000
  warmup_iter: -1  # no warm up
  lr_steps: [100000]
  restarts:
  restart_weights:
  lr_gamma: 0.5
  clear_state: false

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 1000

#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 10000