#!/bin/bash/

#CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_x234 --model RCAN --sInit_value 100 --pre_train ../../RCAN_TrainCode/experiment/RCAN1000n/model/model_best.pt --scale 4 --patch_size 192 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/dml/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set5
#CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_x234 --model RCAN --sInit_value 100 --pre_train ../../RCAN_TrainCode/experiment/RCAN1000n/model/model_best.pt --scale 4 --patch_size 192 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/dml/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set14
#CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_x234 --model RCAN --sInit_value 100 --pre_train ../../RCAN_TrainCode/experiment/RCAN1000n/model/model_best.pt --scale 4 --patch_size 192 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/dml/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset B100
#CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_x234 --model RCAN --sInit_value 100 --pre_train ../../RCAN_TrainCode/experiment/RCAN1000n/model/model_best.pt --scale 4 --patch_size 192 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/dml/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Urban100


#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4005/model/model_best.pt --scale 4 --patch_size 192 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set5
#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4005/model/model_best.pt --scale 4 --patch_size 192 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set14
#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4005/model/model_best.pt --scale 4 --patch_size 192 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset B100
#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4005/model/model_best.pt --scale 4 --patch_size 192 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Urban100
#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4006/model/model_best.pt --scale 3 --patch_size 144 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set5
#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4006/model/model_best.pt --scale 3 --patch_size 144 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set14
#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4006/model/model_best.pt --scale 3 --patch_size 144 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset B100
#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4006/model/model_best.pt --scale 3 --patch_size 144 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Urban100
#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4007/model/model_best.pt --scale 2 --patch_size 96  --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set5
#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4007/model/model_best.pt --scale 2 --patch_size 96  --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set14
#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4007/model/model_best.pt --scale 2 --patch_size 96  --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset B100
#CUDA_VISIBLE_DEVICES=3 python main.py --save EDSR_S60_x234 --template EDSR_paper --sparseMode pw --t0 -12 --pre_train ../../../EDSR_pytorch/experiment/dml4007/model/model_best.pt --scale 2 --patch_size 96  --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Urban100


CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6002/model/model_best_-1.pt --scale 2 --patch_size 96  --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set5
CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6002/model/model_best_-1.pt --scale 2 --patch_size 96  --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set14
CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6002/model/model_best_-1.pt --scale 2 --patch_size 96  --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset B100
CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6002/model/model_best_-1.pt --scale 2 --patch_size 96  --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Urban100
CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6003/model/model_best_-1.pt --scale 3 --patch_size 144 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set5
CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6003/model/model_best_-1.pt --scale 3 --patch_size 144 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set14
CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6003/model/model_best_-1.pt --scale 3 --patch_size 144 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset B100
CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6003/model/model_best_-1.pt --scale 3 --patch_size 144 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Urban100
CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6004/model/model_best_-1.pt --scale 4 --patch_size 192 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set5
CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6004/model/model_best_-1.pt --scale 4 --patch_size 192 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set14
CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6004/model/model_best_-1.pt --scale 4 --patch_size 192 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset B100
CUDA_VISIBLE_DEVICES=0 python main.py --save RCANG5R10_S90_x234 --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6004/model/model_best_-1.pt --scale 4 --patch_size 192 --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Urban100

CUDA_VISIBLE_DEVICES=2 python main.py --save test --model RCAN --sparseMode pw --t0 -12 --pre_train ../../RCAN_TrainCode/experiment/dml6002/model/model_best_-1.pt --scale 2 --patch_size 96  --n_resgroups 5 --n_resblocks 10 --n_feats 64 --test_only --save_results --chop --testpath /home/lxt/RCAN/RCAN_TestCode/LR/LRBI --data_test MyImage --testset Set5
